"""add_color_to_habits

Revision ID: c099653b54d7
Revises: bd43b11caca3
Create Date: 2026-07-06 23:58:36.374287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c099653b54d7'
down_revision: Union[str, Sequence[str], None] = 'bd43b11caca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('color', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'color')
    # ### end Alembic commands ###
