"""add_label_and_day_of_month

Revision ID: dd9aaedfe6a9
Revises: 7f9e2bde8ee3
Create Date: 2026-07-06 04:25:52.230338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9aaedfe6a9'
down_revision: Union[str, Sequence[str], None] = '7f9e2bde8ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('label', sa.String(length=16), nullable=True))
    op.add_column('habits', sa.Column('scheduled_day_of_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'scheduled_day_of_month')
    op.drop_column('habits', 'label')
    # ### end Alembic commands ###
